services:
  mssql-2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    volumes:
      - ./docker/certs:/certs:ro
      - ./docker/docker-mssql.conf:/var/opt/mssql/mssql.conf:ro
    ports:
      - "1433:1433"

  mssql-2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    volumes:
      - ./docker/certs:/certs:ro
      - ./docker/docker-mssql.conf:/var/opt/mssql/mssql.conf:ro
    ports:
      - "1433:1433"

  mssql-2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    volumes:
      - ./docker/certs:/certs:ro
      - ./docker/docker-mssql.conf:/var/opt/mssql/mssql.conf:ro
    ports:
      - "1433:1433"

  mssql-azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
    volumes:
      - ./docker/certs:/certs:ro
      - ./docker/docker-mssql.conf:/var/opt/mssql/mssql.conf:ro
    ports:
      - "1433:1433"
